-- MySQL Script generated by MySQL Workbench
-- Naloga 2 - Nejč
-- Celotna skripta za oddajo

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- =====================================================
-- 1. USTVARJANJE UPORABNIKOV IN PRAVIC
-- =====================================================

-- Brisanje obstoječih uporabnikov (če obstajajo)
DROP USER IF EXISTS 'nejc'@'localhost';
DROP USER IF EXISTS 'readonly'@'localhost';

-- Ustvarjanje uporabnikov in dodelitev pravic
CREATE USER 'nejc'@'localhost' IDENTIFIED BY 'nejc12341';
CREATE USER 'readonly'@'localhost' IDENTIFIED BY 'readonly123';

-- Dodelitev pravic
GRANT SELECT, INSERT, UPDATE, DELETE ON Bolnica.* TO 'nejc'@'localhost';
GRANT SELECT ON Bolnica.* TO 'readonly'@'localhost';

SELECT '=== USTVARJENI UPORABNIKI ===' AS Status;
SELECT user, host FROM mysql.user WHERE user IN ('nejc', 'readonly');

-- =====================================================
-- 2. USTVARJANJE BAZE
-- =====================================================

CREATE DATABASE IF NOT EXISTS `Bolnica` DEFAULT CHARACTER SET utf8;
USE `Bolnica`;

SELECT '=== BAZA BOLNICA USTVARJENA ===' AS Status;

-- =====================================================
-- 3. USTVARJANJE TABEL
-- =====================================================

-- Table Proizvajalec
CREATE TABLE IF NOT EXISTS `Proizvajalec` (
  `idProizvajalec` INT NOT NULL AUTO_INCREMENT,
  `ImeProizvajalca` VARCHAR(45) NOT NULL,
  `Drzava` VARCHAR(45) NULL,
  PRIMARY KEY (`idProizvajalec`)
) ENGINE = InnoDB;

-- Table VrstaOpreme
CREATE TABLE IF NOT EXISTS `VrstaOpreme` (
  `idVrstaOpreme` INT NOT NULL AUTO_INCREMENT,
  `ImeVrste` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVrstaOpreme`)
) ENGINE = InnoDB;

-- Table Oprema
CREATE TABLE IF NOT EXISTS `Oprema` (
  `idOprema` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Serijska_stevilka` VARCHAR(45) NOT NULL,
  `teza` DECIMAL(8,2) NOT NULL,
  `Cena` DECIMAL(10,2) NULL,
  `Proizvajalec_idProizvajalec` INT NOT NULL,
  `VrstaOpreme_idVrstaOpreme` INT NOT NULL,
  PRIMARY KEY (`idOprema`),
  INDEX `fk_Oprema_Proizvajalec1_idx` (`Proizvajalec_idProizvajalec` ASC),
  INDEX `fk_Oprema_VrstaOpreme1_idx` (`VrstaOpreme_idVrstaOpreme` ASC),
  CONSTRAINT `fk_Oprema_Proizvajalec1`
    FOREIGN KEY (`Proizvajalec_idProizvajalec`)
    REFERENCES `Proizvajalec` (`idProizvajalec`),
  CONSTRAINT `fk_Oprema_VrstaOpreme1`
    FOREIGN KEY (`VrstaOpreme_idVrstaOpreme`)
    REFERENCES `VrstaOpreme` (`idVrstaOpreme`)
) ENGINE = InnoDB;

-- Table Stranka
CREATE TABLE IF NOT EXISTS `Stranka` (
  `idStranka` INT NOT NULL AUTO_INCREMENT,
  `ImeStranke` VARCHAR(45) NOT NULL,
  `TipStranke` VARCHAR(45) NOT NULL,
  `Telefon` INT NULL,
  `Naslov` VARCHAR(45) NULL,
  PRIMARY KEY (`idStranka`)
) ENGINE = InnoDB;

-- Table Osebje
CREATE TABLE IF NOT EXISTS `Osebje` (
  `idOsebje` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(45) NOT NULL,
  `Priimek` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOsebje`)
) ENGINE = InnoDB;

-- Table Racun
CREATE TABLE IF NOT EXISTS `Racun` (
  `idRacun` INT NOT NULL AUTO_INCREMENT,
  `StevilkaRacuna` VARCHAR(45) NOT NULL,
  `DatumRacuna` DATE NOT NULL,
  `znesek` DECIMAL(10,2) NOT NULL,
  `Stranka_idStranka` INT NOT NULL,
  `Osebje_idOsebje` INT NOT NULL,
  PRIMARY KEY (`idRacun`),
  INDEX `fk_Racun_Stranka_idx` (`Stranka_idStranka` ASC),
  INDEX `fk_Racun_Osebje1_idx` (`Osebje_idOsebje` ASC),
  CONSTRAINT `fk_Racun_Stranka`
    FOREIGN KEY (`Stranka_idStranka`)
    REFERENCES `Stranka` (`idStranka`),
  CONSTRAINT `fk_Racun_Osebje1`
    FOREIGN KEY (`Osebje_idOsebje`)
    REFERENCES `Osebje` (`idOsebje`)
) ENGINE = InnoDB;

-- Table Racun_Oprema
CREATE TABLE IF NOT EXISTS `Racun_Oprema` (
  `IdRacunOpreme` INT NOT NULL AUTO_INCREMENT,
  `Kolicina` INT NULL,
  `Cena` DECIMAL(10,2) NULL,
  `Oprema_idOprema` INT NOT NULL,
  `Racun_idRacun` INT NOT NULL,
  PRIMARY KEY (`IdRacunOpreme`),
  INDEX `fk_Racun_Oprema_Oprema1_idx` (`Oprema_idOprema` ASC),
  INDEX `fk_Racun_Oprema_Racun1_idx` (`Racun_idRacun` ASC),
  CONSTRAINT `fk_Racun_Oprema_Oprema1`
    FOREIGN KEY (`Oprema_idOprema`)
    REFERENCES `Oprema` (`idOprema`),
  CONSTRAINT `fk_Racun_Oprema_Racun1`
    FOREIGN KEY (`Racun_idRacun`)
    REFERENCES `Racun` (`idRacun`)
) ENGINE = InnoDB;

-- Table Partner
CREATE TABLE IF NOT EXISTS `Partner` (
  `idPartner` INT NOT NULL AUTO_INCREMENT,
  `ImePartnerja` VARCHAR(45) NOT NULL,
  `Naslov` VARCHAR(45) NULL,
  `Telefon` INT NULL,
  PRIMARY KEY (`idPartner`)
) ENGINE = InnoDB;

-- Table SestavniDel
CREATE TABLE IF NOT EXISTS `SestavniDel` (
  `idSestavniDel` INT NOT NULL AUTO_INCREMENT,
  `ImeDela` VARCHAR(45) NOT NULL,
  `Opis` VARCHAR(45) NULL,
  `Zaloga` INT NULL,
  `MinZaloga` INT NULL,
  `Partner_idPartner` INT NOT NULL,
  PRIMARY KEY (`idSestavniDel`),
  INDEX `fk_SestavniDel_Partner1_idx` (`Partner_idPartner` ASC),
  CONSTRAINT `fk_SestavniDel_Partner1`
    FOREIGN KEY (`Partner_idPartner`)
    REFERENCES `Partner` (`idPartner`)
) ENGINE = InnoDB;

-- Table Dobavnica
CREATE TABLE IF NOT EXISTS `Dobavnica` (
  `idDobavnica` INT NOT NULL AUTO_INCREMENT,
  `StevilkaDobavnice` INT NOT NULL,
  `DatumDobavnice` DATE NULL,
  `Znesek` DECIMAL(10,2) NULL,
  `Stranka_idStranka` INT NOT NULL,
  `Osebje_idOsebje` INT NOT NULL,
  PRIMARY KEY (`idDobavnica`),
  INDEX `fk_Dobavnica_Stranka1_idx` (`Stranka_idStranka` ASC),
  INDEX `fk_Dobavnica_Osebje1_idx` (`Osebje_idOsebje` ASC),
  CONSTRAINT `fk_Dobavnica_Stranka1`
    FOREIGN KEY (`Stranka_idStranka`)
    REFERENCES `Stranka` (`idStranka`),
  CONSTRAINT `fk_Dobavnica_Osebje1`
    FOREIGN KEY (`Osebje_idOsebje`)
    REFERENCES `Osebje` (`idOsebje`)
) ENGINE = InnoDB;

-- Table Narocila
CREATE TABLE IF NOT EXISTS `Narocila` (
  `idNarocila` INT NOT NULL AUTO_INCREMENT,
  `DatumNarocila` DATE NOT NULL,
  `Znesek` DECIMAL(10,2) NULL,
  `Status` VARCHAR(45) NULL,
  `Partner_idPartner` INT NOT NULL,
  PRIMARY KEY (`idNarocila`),
  INDEX `fk_Narocila_Partner1_idx` (`Partner_idPartner` ASC),
  CONSTRAINT `fk_Narocila_Partner1`
    FOREIGN KEY (`Partner_idPartner`)
    REFERENCES `Partner` (`idPartner`)
) ENGINE = InnoDB;

-- Table Dobavnica_SestavniDel
CREATE TABLE IF NOT EXISTS `Dobavnica_SestavniDel` (
  `idDobavnica_SestavniDel` INT NOT NULL AUTO_INCREMENT,
  `Kolicina` INT NOT NULL,
  `Cena` DECIMAL(10,2) NOT NULL,
  `Dobavnica_idDobavnica` INT NOT NULL,
  `SestavniDel_idSestavniDel` INT NOT NULL,
  PRIMARY KEY (`idDobavnica_SestavniDel`),
  INDEX `fk_Dobavnica_SestavniDel_Dobavnica1_idx` (`Dobavnica_idDobavnica` ASC),
  INDEX `fk_Dobavnica_SestavniDel_SestavniDel1_idx` (`SestavniDel_idSestavniDel` ASC),
  CONSTRAINT `fk_Dobavnica_SestavniDel_Dobavnica1`
    FOREIGN KEY (`Dobavnica_idDobavnica`)
    REFERENCES `Dobavnica` (`idDobavnica`),
  CONSTRAINT `fk_Dobavnica_SestavniDel_SestavniDel1`
    FOREIGN KEY (`SestavniDel_idSestavniDel`)
    REFERENCES `SestavniDel` (`idSestavniDel`)
) ENGINE = InnoDB;

-- Table Oprema_SestavniDel
CREATE TABLE IF NOT EXISTS `Oprema_SestavniDel` (
  `idOprema_SestavniDel` INT NOT NULL AUTO_INCREMENT,
  `Kolicina` INT NULL,
  `SestavniDel_idSestavniDel` INT NOT NULL,
  `Oprema_idOprema` INT NOT NULL,
  PRIMARY KEY (`idOprema_SestavniDel`),
  INDEX `fk_Oprema_SestavniDel_SestavniDel1_idx` (`SestavniDel_idSestavniDel` ASC),
  INDEX `fk_Oprema_SestavniDel_Oprema1_idx` (`Oprema_idOprema` ASC),
  CONSTRAINT `fk_Oprema_SestavniDel_SestavniDel1`
    FOREIGN KEY (`SestavniDel_idSestavniDel`)
    REFERENCES `SestavniDel` (`idSestavniDel`),
  CONSTRAINT `fk_Oprema_SestavniDel_Oprema1`
    FOREIGN KEY (`Oprema_idOprema`)
    REFERENCES `Oprema` (`idOprema`)
) ENGINE = InnoDB;

-- Table Oprema_Partner
CREATE TABLE IF NOT EXISTS `Oprema_Partner` (
  `idOprema_Partner` INT NOT NULL AUTO_INCREMENT,
  `Oprema_idOprema` INT NOT NULL,
  `Partner_idPartner` INT NOT NULL,
  PRIMARY KEY (`idOprema_Partner`),
  INDEX `fk_Oprema_Partner_Oprema1_idx` (`Oprema_idOprema` ASC),
  INDEX `fk_Oprema_Partner_Partner1_idx` (`Partner_idPartner` ASC),
  CONSTRAINT `fk_Oprema_Partner_Oprema1`
    FOREIGN KEY (`Oprema_idOprema`)
    REFERENCES `Oprema` (`idOprema`),
  CONSTRAINT `fk_Oprema_Partner_Partner1`
    FOREIGN KEY (`Partner_idPartner`)
    REFERENCES `Partner` (`idPartner`)
) ENGINE = InnoDB;

-- Table SestavniDel_Partner
CREATE TABLE IF NOT EXISTS `SestavniDel_Partner` (
  `idSestavniDel_Partner` INT NOT NULL AUTO_INCREMENT,
  `SestavniDel_idSestavniDel` INT NOT NULL,
  `Partner_idPartner` INT NOT NULL,
  PRIMARY KEY (`idSestavniDel_Partner`),
  INDEX `fk_SestavniDel_Partner_SestavniDel1_idx` (`SestavniDel_idSestavniDel` ASC),
  INDEX `fk_SestavniDel_Partner_Partner1_idx` (`Partner_idPartner` ASC),
  CONSTRAINT `fk_SestavniDel_Partner_SestavniDel1`
    FOREIGN KEY (`SestavniDel_idSestavniDel`)
    REFERENCES `SestavniDel` (`idSestavniDel`),
  CONSTRAINT `fk_SestavniDel_Partner_Partner1`
    FOREIGN KEY (`Partner_idPartner`)
    REFERENCES `Partner` (`idPartner`)
) ENGINE = InnoDB;

SELECT '=== VSE TABLELE USPEŠNO USTVARJENE ===' AS Status;
SELECT COUNT(*) AS 'Število tabel' FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Bolnica';

-- =====================================================
-- 4. VSTAVLJANJE TESTNIH PODATKOV
-- =====================================================

-- Tabele brez tujih ključev (vsaj 5 vnosov)
INSERT INTO `Proizvajalec` (`ImeProizvajalca`, `Drzava`) VALUES
('Bosch', 'Nemčija'),
('Makita', 'Japonska'),
('Stanley', 'ZDA'),
('Einhell', 'Nemčija'),
('Metabo', 'Nemčija');

INSERT INTO `VrstaOpreme` (`ImeVrste`) VALUES
('Električno orodje'),
('Ročno orodje'),
('Merilna oprema'),
('Varovalna oprema'),
('Dodatki');

INSERT INTO `Stranka` (`ImeStranke`, `TipStranke`, `Telefon`, `Naslov`) VALUES
('Gradbeništvo Kralj', 'Podjetje', 12345678, 'Cvetkova ulica 12'),
('Elektro Maribor', 'Podjetje', 23456789, 'Ulica heroja 5'),
('Janez Novak', 'Zasebnik', 34567890, 'Rožna dolina 8'),
('Štukaterstvo Planinc', 'Podjetje', 45678901, 'Industrijska cona 15'),
('Mizarstvo Lesnik', 'Podjetje', 56789012, 'Gajev trg 3');

INSERT INTO `Osebje` (`Ime`, `Priimek`) VALUES
('Marko', 'Novak'),
('Ana', 'Kovač'),
('Peter', 'Horvat'),
('Maja', 'Potokar'),
('Luka', 'Zupan');

INSERT INTO `Partner` (`ImePartnerja`, `Naslov`, `Telefon`) VALUES
('TechSupply d.o.o.', 'Ljubljanska cesta 15', 31456789),
('ElektroKomponent', 'Mariborska ulica 22', 25678901),
('GlobalParts', 'Celovška 128', 17890123),
('MetalIndust', 'Tržaška 45', 49012345),
('PlastTech', 'Dunajska 67', 51234567);

-- Tabele s tujimi ključi (vsaj 10 vnosov)
INSERT INTO `Oprema` (`Ime`, `Serijska_stevilka`, `teza`, `Cena`, `Proizvajalec_idProizvajalec`, `VrstaOpreme_idVrstaOpreme`) VALUES
('Vrtalni stroj BHD', 'VS2024001', 2.5, 189.99, 1, 1),
('Ključavničarski stroj', 'KS2024002', 4.2, 349.50, 2, 1),
('Merilna tračnica', 'MT2024003', 1.8, 45.75, 3, 3),
('Varovalna čelada', 'VC2024004', 0.5, 22.99, 4, 4),
('Ročna žaga', 'RZ2024005', 3.1, 129.99, 5, 2),
('Multimeter digitalni', 'MM2024006', 0.3, 89.50, 1, 3),
('Brusilnik', 'BR2024007', 2.8, 199.99, 2, 1),
('Kompresor', 'KP2024008', 15.5, 459.00, 3, 1),
('Vijaknik udarni', 'VU2024009', 2.2, 279.50, 4, 1),
('Set ključev', 'SK2024010', 2.0, 75.25, 5, 2);

INSERT INTO `SestavniDel` (`ImeDela`, `Opis`, `Zaloga`, `MinZaloga`, `Partner_idPartner`) VALUES
('Motor 1000W', 'Univerzalni elektromotor', 25, 5, 1),
('Baterija Li-ion', '18V 5.0Ah baterija', 40, 10, 2),
('Stikalo', 'Vklopno-izklopno stikalo', 100, 20, 3),
('Žica 2.5mm', 'Bakrena žica za napajanje', 200, 50, 1),
('Vijak M6x20', 'Jekleni vijak', 500, 100, 4),
('Ležaj 6202', 'Kroglični ležaj', 80, 15, 5),
('Ohišje plastično', 'Zaščitno ohišje', 60, 10, 4),
('Kabel 3-pin', 'Napajalni kabel', 120, 25, 2),
('Pnevmatika', 'Zračni filter', 45, 8, 3),
('Display LCD', 'Digitalni display', 30, 5, 1);

INSERT INTO `Racun` (`StevilkaRacuna`, `DatumRacuna`, `znesek`, `Stranka_idStranka`, `Osebje_idOsebje`) VALUES
('RAC-2024-001', '2024-01-15', 534.48, 1, 1),
('RAC-2024-002', '2024-01-16', 129.99, 3, 2),
('RAC-2024-003', '2024-01-18', 899.49, 2, 3),
('RAC-2024-004', '2024-01-20', 225.74, 4, 1),
('RAC-2024-005', '2024-01-22', 459.00, 5, 4),
('RAC-2024-006', '2024-01-25', 168.75, 1, 2),
('RAC-2024-007', '2024-01-28', 349.50, 3, 3),
('RAC-2024-008', '2024-02-01', 199.99, 2, 1),
('RAC-2024-009', '2024-02-03', 89.50, 4, 4),
('RAC-2024-010', '2024-02-05', 75.25, 5, 2);

INSERT INTO `Narocila` (`DatumNarocila`, `Znesek`, `Status`, `Partner_idPartner`) VALUES
('2024-01-05', 1500.00, 'Dokončano', 1),
('2024-01-08', 800.50, 'V obdelavi', 2),
('2024-01-10', 1200.75, 'Dokončano', 3),
('2024-01-12', 950.25, 'Stornirano', 4),
('2024-01-15', 600.00, 'Dokončano', 5),
('2024-01-18', 1350.40, 'V obdelavi', 1),
('2024-01-20', 720.80, 'Dokončano', 2),
('2024-01-22', 1100.60, 'Čaka na plačilo', 3),
('2024-01-25', 480.90, 'Dokončano', 4),
('2024-01-28', 920.30, 'V obdelavi', 5);

INSERT INTO `Dobavnica` (`StevilkaDobavnice`, `DatumDobavnice`, `Znesek`, `Stranka_idStranka`, `Osebje_idOsebje`) VALUES
(1001, '2024-01-10', 1200.50, 1, 1),
(1002, '2024-01-12', 850.75, 2, 2),
(1003, '2024-01-15', 450.25, 3, 3),
(1004, '2024-01-18', 980.00, 4, 4),
(1005, '2024-01-20', 320.80, 5, 1),
(1006, '2024-01-22', 765.40, 1, 2),
(1007, '2024-01-25', 1120.90, 2, 3),
(1008, '2024-01-28', 540.60, 3, 4),
(1009, '2024-02-01', 890.30, 4, 1),
(1010, '2024-02-03', 670.45, 5, 2);

-- Vmesne tabele
INSERT INTO `Racun_Oprema` (`Kolicina`, `Cena`, `Oprema_idOprema`, `Racun_idRacun`) VALUES
(2, 189.99, 1, 1),
(1, 129.99, 5, 2),
(1, 349.50, 2, 3),
(1, 459.00, 8, 3),
(3, 45.75, 3, 4),
(1, 89.50, 6, 5),
(2, 22.99, 4, 6),
(1, 199.99, 7, 7),
(1, 279.50, 9, 8),
(1, 75.25, 10, 9);

INSERT INTO `Dobavnica_SestavniDel` (`Kolicina`, `Cena`, `Dobavnica_idDobavnica`, `SestavniDel_idSestavniDel`) VALUES
(10, 45.50, 1, 1),
(25, 12.80, 1, 2),
(50, 3.20, 2, 3),
(100, 1.50, 2, 4),
(15, 28.75, 3, 5),
(20, 8.90, 3, 6),
(30, 15.40, 4, 7),
(40, 6.25, 4, 8),
(12, 32.10, 5, 9),
(8, 45.00, 5, 10);

INSERT INTO `SestavniDel_Partner` (`SestavniDel_idSestavniDel`, `Partner_idPartner`) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 1),
(5, 4),
(6, 5),
(7, 4),
(8, 2),
(9, 3),
(10, 1);

INSERT INTO `Oprema_Partner` (`Oprema_idOprema`, `Partner_idPartner`) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 1),
(7, 2),
(8, 3),
(9, 4),
(10, 5);

INSERT INTO `Oprema_SestavniDel` (`Kolicina`, `SestavniDel_idSestavniDel`, `Oprema_idOprema`) VALUES
(1, 1, 1),
(2, 2, 1),
(1, 3, 1),
(1, 1, 2),
(2, 2, 2),
(1, 4, 2),
(1, 5, 3),
(1, 6, 4),
(2, 7, 5),
(1, 8, 6);

SELECT '=== TESTNI PODATKI USPEŠNO VSTAVLJENI ===' AS Status;

-- =====================================================
-- 5. PREVERJANJE IZPISA
-- =====================================================

SELECT '=== PREVERJANJE TABEL ===' AS Status;

SELECT 'Proizvajalec (5 vnosov):' AS Tabela; 
SELECT * FROM `Proizvajalec`;
SELECT COUNT(*) AS 'Število vnosov' FROM `Proizvajalec`;

SELECT 'Oprema (10 vnosov):' AS Tabela; 
SELECT * FROM `Oprema`;
SELECT COUNT(*) AS 'Število vnosov' FROM `Oprema`;

SELECT 'Stranka (5 vnosov):' AS Tabela; 
SELECT * FROM `Stranka`;
SELECT COUNT(*) AS 'Število vnosov' FROM `Stranka`;

SELECT 'Racun (10 vnosov):' AS Tabela; 
SELECT * FROM `Racun`;
SELECT COUNT(*) AS 'Število vnosov' FROM `Racun`;

-- =====================================================
-- 6. PREVERJANJE PRAVIC UPORABNIKOV
-- =====================================================

SELECT '=== PREVERJANJE PRAVIC UPORABNIKOV ===' AS Status;

SELECT 'Pravice uporabnika nejc:' AS Status; 
SHOW GRANTS FOR 'nejc'@'localhost';

SELECT 'Pravice uporabnika readonly:' AS Status; 
SHOW GRANTS FOR 'readonly'@'localhost';

-- =====================================================
-- 7. KONČNO POROČILO
-- =====================================================

SELECT '=== KONČNO POROČILO ===' AS Status;
SELECT 
    (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Bolnica') AS 'Št. tabel',
    (SELECT COUNT(*) FROM mysql.user WHERE user IN ('nejc', 'readonly')) AS 'Št. uporabnikov',
    (SELECT COUNT(*) FROM Proizvajalec) AS 'Proizvajalci',
    (SELECT COUNT(*) FROM Oprema) AS 'Oprema',
    'NALOGA USPEŠNO IZVEDENA' AS Status;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;