// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BazaContext))]
    partial class BazaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Backend.Entitete.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Do")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImeGosta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Od")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opomba")
                        .HasColumnType("TEXT");

                    b.Property<int>("SobaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SobaId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Backend.Entitete.Soba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CenaNaNoc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kapaciteta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stevilka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sobe");
                });

            modelBuilder.Entity("Backend.Entitete.Rezervacija", b =>
                {
                    b.HasOne("Backend.Entitete.Soba", "Soba")
                        .WithMany("Rezervacije")
                        .HasForeignKey("SobaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soba");
                });

            modelBuilder.Entity("Backend.Entitete.Soba", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
