-- MySQL Script generated by MySQL Workbench
-- Mon Mar 23 19:16:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Drzava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drzava` (
  `idDrzava` INT NOT NULL,
  `Ime_Drzave` VARCHAR(100) NULL,
  `Koda_Drzave` VARCHAR(45) NULL,
  PRIMARY KEY (`idDrzava`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tekmovalci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tekmovalci` (
  `idTekmovalci` INT NOT NULL,
  `Ime_Priimek` VARCHAR(45) NOT NULL,
  `Spol` VARCHAR(45) NULL,
  `Drzava_idDrzava` INT NOT NULL,
  PRIMARY KEY (`idTekmovalci`),
  INDEX `fk_Tekmovalci_Drzava1_idx` (`Drzava_idDrzava` ASC) VISIBLE,
  CONSTRAINT `fk_Tekmovalci_Drzava1`
    FOREIGN KEY (`Drzava_idDrzava`)
    REFERENCES `mydb`.`Drzava` (`idDrzava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tip_Tekmovanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tip_Tekmovanja` (
  `idTip_Tekmovanja` INT NOT NULL,
  `Tip` VARCHAR(45) NULL,
  PRIMARY KEY (`idTip_Tekmovanja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tekma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tekma` (
  `idTekma` INT NOT NULL,
  `Ime_tekme` VARCHAR(255) NOT NULL,
  `Leto` INT NULL,
  `Lokacija` VARCHAR(45) NULL,
  `Latituda` DECIMAL(10,8) NULL,
  `Longituda` DECIMAL(11,8) NULL,
  `Tip_Tekmovanja_idTip_Tekmovanja` INT NOT NULL,
  `Drzava_idDrzava` INT NOT NULL,
  PRIMARY KEY (`idTekma`),
  INDEX `fk_Tekma_Tip_Tekmovanja1_idx` (`Tip_Tekmovanja_idTip_Tekmovanja` ASC) VISIBLE,
  INDEX `fk_Tekma_Drzava1_idx` (`Drzava_idDrzava` ASC) VISIBLE,
  CONSTRAINT `fk_Tekma_Tip_Tekmovanja1`
    FOREIGN KEY (`Tip_Tekmovanja_idTip_Tekmovanja`)
    REFERENCES `mydb`.`Tip_Tekmovanja` (`idTip_Tekmovanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tekma_Drzava1`
    FOREIGN KEY (`Drzava_idDrzava`)
    REFERENCES `mydb`.`Drzava` (`idDrzava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezultati`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rezultati` (
  `idRezultata` INT NOT NULL,
  `Stevilka` INT NULL,
  `Cas_Plavanja` VARCHAR(45) NULL,
  `Cas_Kolesarjenja` VARCHAR(45) NULL,
  `Cas_Teka` VARCHAR(45) NULL,
  `Skupni_cas` VARCHAR(45) NULL,
  `Uvrstitev` INT NULL,
  `Uvrstitev_spol` VARCHAR(45) NULL,
  `Uvrstitev_Kategorija` VARCHAR(45) NULL,
  `Kategorija` VARCHAR(45) NULL,
  `Tekma_idTekma` INT NOT NULL,
  `Tip_Tekmovanja_idTip_Tekmovanja` INT NOT NULL,
  `Tekmovalci_idTekmovalci` INT NOT NULL,
  PRIMARY KEY (`idRezultata`),
  INDEX `fk_Rezultati_Tekma1_idx` (`Tekma_idTekma` ASC) VISIBLE,
  INDEX `fk_Rezultati_Tip_Tekmovanja1_idx` (`Tip_Tekmovanja_idTip_Tekmovanja` ASC) VISIBLE,
  INDEX `fk_Rezultati_Tekmovalci1_idx` (`Tekmovalci_idTekmovalci` ASC) VISIBLE,
  CONSTRAINT `fk_Rezultati_Tekma1`
    FOREIGN KEY (`Tekma_idTekma`)
    REFERENCES `mydb`.`Tekma` (`idTekma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezultati_Tip_Tekmovanja1`
    FOREIGN KEY (`Tip_Tekmovanja_idTip_Tekmovanja`)
    REFERENCES `mydb`.`Tip_Tekmovanja` (`idTip_Tekmovanja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezultati_Tekmovalci1`
    FOREIGN KEY (`Tekmovalci_idTekmovalci`)
    REFERENCES `mydb`.`Tekmovalci` (`idTekmovalci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
