// <auto-generated />
using System;
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BazaContext))]
    [Migration("20260204093015_Inicializacija")]
    partial class Inicializacija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Backend.Entitete.Nabiralnik", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Nabiralniki");
                });

            modelBuilder.Entity("Backend.Entitete.Sporocilo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CasPosiljanja")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosiljateljEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrejemnikEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vsebina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zadeva")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PosiljateljEmail");

                    b.HasIndex("PrejemnikEmail");

                    b.ToTable("Sporocila");
                });

            modelBuilder.Entity("Backend.Entitete.Sporocilo", b =>
                {
                    b.HasOne("Backend.Entitete.Nabiralnik", "Posiljatelj")
                        .WithMany("PoslanaSporocila")
                        .HasForeignKey("PosiljateljEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Entitete.Nabiralnik", "Prejemnik")
                        .WithMany("PrejetaSporocila")
                        .HasForeignKey("PrejemnikEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Posiljatelj");

                    b.Navigation("Prejemnik");
                });

            modelBuilder.Entity("Backend.Entitete.Nabiralnik", b =>
                {
                    b.Navigation("PoslanaSporocila");

                    b.Navigation("PrejetaSporocila");
                });
#pragma warning restore 612, 618
        }
    }
}
