// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vaja4NalogaTest;

#nullable disable

namespace Vaja4NalogaTest.Migrations
{
    [DbContext(typeof(PdBaza))]
    [Migration("20251212175836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Vaja4NalogaTest.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avtor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumIzdelave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VseKnjige");
                });
#pragma warning restore 612, 618
        }
    }
}
