// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vaja4NalogaTest;

#nullable disable

namespace Vaja4NalogaTest.Migrations
{
    [DbContext(typeof(PdBaza))]
    [Migration("20251213095743_AddPublisher")]
    partial class AddPublisher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Vaja4NalogaTest.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avtor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumIzdelave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZaloznikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZaloznikId");

                    b.ToTable("VseKnjige");
                });

            modelBuilder.Entity("Vaja4NalogaTest.Zaloznik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VsiZaložniki");
                });

            modelBuilder.Entity("Vaja4NalogaTest.Knjiga", b =>
                {
                    b.HasOne("Vaja4NalogaTest.Zaloznik", "Zaloznik")
                        .WithMany("Knjige")
                        .HasForeignKey("ZaloznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zaloznik");
                });

            modelBuilder.Entity("Vaja4NalogaTest.Zaloznik", b =>
                {
                    b.Navigation("Knjige");
                });
#pragma warning restore 612, 618
        }
    }
}
