// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vaja4NalogaTest;

#nullable disable

namespace Vaja4NalogaTest.Migrations
{
    [DbContext(typeof(PdBaza))]
    partial class PdBazaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Vaja4NalogaTest.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avtor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumIzdelave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZaloznikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZaloznikId");

                    b.ToTable("VseKnjige");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avtor = "Jules Verne",
                            DatumIzdelave = new DateTime(2025, 12, 15, 13, 6, 57, 672, DateTimeKind.Local).AddTicks(2749),
                            Naslov = "Potovanje na luno",
                            ZaloznikId = 2
                        });
                });

            modelBuilder.Entity("Vaja4NalogaTest.Zaloznik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VsiZaložniki");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Založba Modrijan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mladinska Knjiga"
                        });
                });

            modelBuilder.Entity("Vaja4NalogaTest.Knjiga", b =>
                {
                    b.HasOne("Vaja4NalogaTest.Zaloznik", "Zaloznik")
                        .WithMany("Knjige")
                        .HasForeignKey("ZaloznikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zaloznik");
                });

            modelBuilder.Entity("Vaja4NalogaTest.Zaloznik", b =>
                {
                    b.Navigation("Knjige");
                });
#pragma warning restore 612, 618
        }
    }
}
