// <auto-generated />
using AIS_16_10_3;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIS_16_10_3.Migrations
{
    [DbContext(typeof(BazaContext))]
    [Migration("20260208133719_Kosarica")]
    partial class Kosarica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("AIS_16_10_3.Artikel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KosaricaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KosaricaId");

                    b.ToTable("artikli");
                });

            modelBuilder.Entity("AIS_16_10_3.Kosarica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("kosarice");
                });

            modelBuilder.Entity("AIS_16_10_3.Artikel", b =>
                {
                    b.HasOne("AIS_16_10_3.Kosarica", null)
                        .WithMany("SeznamArtiklov")
                        .HasForeignKey("KosaricaId");
                });

            modelBuilder.Entity("AIS_16_10_3.Kosarica", b =>
                {
                    b.Navigation("SeznamArtiklov");
                });
#pragma warning restore 612, 618
        }
    }
}
